#!/usr/bin/env bash

umbrel_dir="$HOME/umbrel"

if [ ! -d "$umbrel_dir" ]; then
  read -p "Please enter the path to your umbrel directory: " umbrel_dir
fi

cp umbrel-cli.py "$umbrel_dir/bin"
chmod +x "$umbrel_dir/bin/umbrel-cli.py"

ln -s "$umbrel_dir/bin/umbrel-cli.py" /usr/local/bin/umbrel

umbrel --version