#!/usr/bin/env bash

UMBREL_DIR="$HOME/umbrel"

if [ ! -d "$UMBREL_DIR" ]; then
  read -p "Please enter the path to your umbrel directory: " UMBREL_DIR
fi

sudo cp umbrel-cli.py "$UMBREL_DIR/scripts"
sudo chmod +x "$UMBREL_DIR/scripts/umbrel-cli.py"

if [ -f "/usr/local/bin/umbrel" ]; then
  sudo rm /usr/local/bin/umbrel
fi

sudo ln -s "$UMBREL_DIR/scripts/umbrel-cli.py" /usr/local/bin/umbrel

umbrel --version

export UMBREL_DIR=${UMBREL_DIR:-$HOME/umbrel}
